# Generated by Django 5.1.1 on 2025-01-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_students_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='roll_number',
            field=models.IntegerField(),
        ),
    ]
